"""Domain contracts for the modular weekly galgame image prescan."""

from .domain import (
    CollectionContext,
    CollectionResult,
    CurationResult,
    DiscoveryMethod,
    EventType,
    FailureRecord,
    FailureStage,
    HistoricalImage,
    ImageCandidate,
    ImageNeed,
    Issue,
    IssueDraft,
    NewsDraft,
    NewsItem,
    NewsResult,
    OutputManifest,
    PipelineResult,
    ReviewReason,
    ScoreBreakdown,
    SearchResult,
    SourceRef,
    SourceType,
    candidate_id_for,
    news_id_for,
)

__all__ = [
    "CollectionContext",
    "CollectionResult",
    "CurationResult",
    "DiscoveryMethod",
    "EventType",
    "FailureRecord",
    "FailureStage",
    "HistoricalImage",
    "ImageCandidate",
    "ImageNeed",
    "Issue",
    "IssueDraft",
    "NewsDraft",
    "NewsItem",
    "NewsResult",
    "OutputManifest",
    "PipelineResult",
    "ReviewReason",
    "ScoreBreakdown",
    "SearchResult",
    "SourceRef",
    "SourceType",
    "candidate_id_for",
    "news_id_for",
]
